project:
  type: website
  output-dir: docs

website:
  title: "Aspen Ellis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Current Research
      - href: publications.qmd
        text: Scientific Publications

format:
  html:
    theme: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

