---
title: "About Me"
---

I am currently a PhD candidate at the University of California, Santa Cruz. Before starting my graduate program, I spent a decade studying seabird colonies on remote islands, where again and again I found myself documenting the impacts of climate change on these systems. To preserve these species, we need to reduce our fossil fuel emissions – but development of renewable energy may have immediate negative impacts on wildlife. My research now focuses on understanding the impacts of offshore wind energy to seabirds, and developing plans to offset those impacts so that our transition to renewable energy development really can be a net positive for wildlife.

I love working in conservation ecology, and I’m committed to making this field more accessible to future generations of scientists. I’ve co-developed a course on [Queer Ecologies](https://allisonpayne.github.io/queerecologies/) with my collaborator, [Allison Payne](https://allisonpayne.github.io) , that uplifts queer voices in our field and creates a space for undergraduates to explore how queerness intersects with ecology and how broadening perspectives in our field leads to better science. I’m also passionate about improving access to graduate school and retention in graduate programs, and serve as a union steward to help organize students to fight for fair pay and better working conditions.
