---
title: "Publications"
toc: false
---

[ORCID](https://orcid.org/0000-0002-9006-2365){target="_blank"} \| [Google Scholar](https://scholar.google.com/citations?user=ygfF4fkAAAAJ&hl=en&oi=ao){target="_blank"} \| [Research Gate](https://www.researchgate.net/profile/Aspen-Ellis){target="_blank"}

#### Published:

3.   **Ellis, A.A.,** Beck, J.N., Howard, E.A., Rabearisoa, A.L., Alissa, L.M., Barasi, S., Beltran, R.S., Bernardi, G., Bernier, K., Cronin, M.R., Cruz, N., Flores, I.T., Gerraty, F.D., Goetz, L.C., Harenčár, J.G., Kroeker, K.J., Kurle, C.M., Lai, E.Y., Lederman-Beach, R., Malakooti, N.J.V., Mason, S.E., McElfish, M.M., McNelis, M.G., Molinari, M.M., Munro, C.M.O., Nazario, E.C., Payne, A.R., Poudel, S., Rivera, M.G., Slimp, M.C., Sridhar, N.M., Tershy, B.R., Third, G.M., Uckele, K.A., Vilches, F.O., Walker, B.J., Wishingrad, V., Witte, E.C., Yeager, M.E., Young, J.K., Zilliacus, K.M., Croll, D.A.. (2024). Coalition-Building for Labor Actions in Life Sciences Departments: Lessons from the Largest Academic Strike in History. *BioScience.* \[[PDF](https://www.researchgate.net/publication/387024820_Coalition-building_for_labor_actions_in_life_sciences_departments_lessons_from_the_largest_academic_strike_in_history#fullTextFileContent){target="_blank"}\] 

2.   Croll, D.A., **Ellis, A.A.,** Adams, J., Cook, A.S.C.P., Garthe, S., Goodale, M.W., Hall, S., Hazen, E., Keitt, B.S., Kelsey, E.C., Leirness, J.B., Lyons, D.E., McKown, M.W., Potiek, A., Searle, K.R., Soudijn, F.H., Rockwood, R.C., Tershy, B.R., Tinker, M., VanderWerf, E.A., Williams, K.A., Young, L., Zilliacus, K.M. (2022). Framework for Assessing and Mitigating the Impacts of Offshore Wind Energy Development on Marine Birds. *Biological Conservation.* \[[PDF](https://www.researchgate.net/publication/365288795_Framework_for_assessing_and_mitigating_the_impacts_of_offshore_wind_energy_development_on_marine_birds){target="_blank"}\]

1.   Weeks, B.C., Willard, D.E., Zimova, M., **Ellis, A.A.,** Witynski, M.L., Hennen, M., Winger, B.M. (2020). Shared Morphological Consequences of Global Warming in North American Migratory Birds. *Ecology Letters.* \[[PDF](https://www.researchgate.net/publication/337754916_Shared_morphological_consequences_of_global_warming_in_North_American_migratory_birds_Recent_morphological_shifts_in_migratory_birds){target="_blank"}\]
